name = "STMMRunner"
uuid = "5a832f93-9be3-4627-b47e-d2e960387a5d"
authors = ["Gabriel Wu <wuzihua@pku.edu.cn> and contributors"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
julia = "1.8"
DocStringExtensions = "0.8, 0.9"
